name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        run: composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Install front-end dependencies
        run: |
          npm install
          npm run production

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Save Container Registry Config
        run: doctl registry login

      - name: Copy config to secret
        run: echo "${{ secrets.ENV }}" > .env

      - name: Build Docker Container
        run: docker build . -t registry.digitalocean.com/lewis/backend.dobercorgi.info

      - name: Push Container
        run: docker push registry.digitalocean.com/lewis/backend.dobercorgi.info
